-- Baseline pointer for the Postgres DDL (PRD §8 / ARCHITECTURE.md §3.5).
--
-- Apply path: `pnpm db:migrate` runs ordered files under migrations/.
-- Do not add DDL here — add a new numbered file in migrations/ (e.g. 002_….sql).
--
-- Current full baseline: migrations/001_init.sql
